"""Team skill runner for automation steps."""

from __future__ import annotations

import argparse
import os
import subprocess
import tempfile
from pathlib import Path


class SkillRunnerError(RuntimeError):
    """Raised when a skill step command fails."""


def main() -> None:
    """CLI entrypoint for skill step execution."""
    parser = argparse.ArgumentParser(description="Team skill runner")
    subparsers = parser.add_subparsers(dest="step", required=True)

    run_agent_parser = subparsers.add_parser("run-agent")
    run_agent_parser.add_argument(
        "--agent-command",
        default=os.getenv("AUTOMATION_AGENT_COMMAND", ""),
    )

    quality_parser = subparsers.add_parser("quality-gate")
    quality_parser.add_argument(
        "--commands",
        default=os.getenv("AUTOMATION_QUALITY_COMMANDS", "make lint;;make test"),
    )

    commit_parser = subparsers.add_parser("commit-and-push")
    commit_parser.add_argument("--issue-number", required=True)
    commit_parser.add_argument("--branch-name", required=True)

    args = parser.parse_args()

    try:
        if args.step == "run-agent":
            run_agent(args.agent_command)
            return
        if args.step == "quality-gate":
            run_quality_gate(args.commands)
            return
        if args.step == "commit-and-push":
            run_commit_and_push(args.issue_number, args.branch_name)
            return
        raise SkillRunnerError(f"Unsupported step: {args.step}")
    except SkillRunnerError as exc:
        raise SystemExit(str(exc)) from exc


def run_agent(agent_command: str) -> None:
    """Execute the configured agent command."""
    command = agent_command.strip()
    if not command:
        raise SkillRunnerError("Missing AUTOMATION_AGENT_COMMAND for run-agent step")

    result = _exec_shell(command, cwd=Path.cwd())
    if result.returncode != 0:
        raise SkillRunnerError(_format_failure("run-agent", command, result))


def run_quality_gate(commands: str) -> None:
    """Run quality commands sequentially."""
    parsed = [part.strip() for part in commands.split(";;") if part.strip()]
    if not parsed:
        raise SkillRunnerError("No quality commands provided")

    for command in parsed:
        result = _exec_shell(command, cwd=Path.cwd())
        if result.returncode != 0:
            raise SkillRunnerError(_format_failure("quality-gate", command, result))


def run_commit_and_push(issue_number: str, branch_name: str) -> None:
    """Create conventional commit and push branch."""
    _run_checked("git add -A")

    staged_check = _exec_shell("git diff --cached --quiet", cwd=Path.cwd())
    if staged_check.returncode == 0:
        raise SkillRunnerError("No staged changes to commit")

    commit_subject = f"fix(issue-{issue_number}): automated update"
    commit_body = "\n".join(
        [
            commit_subject,
            "",
            "Summary:",
            "- Automated skill-based commit generated by runner",
            "",
            "Tests:",
            "- Delegated to quality-gate step",
            "",
            "Co-authored-by: Codex <codex@openai.com>",
        ]
    )

    with tempfile.NamedTemporaryFile(mode="w", encoding="utf-8", delete=False) as file:
        file.write(commit_body)
        message_path = Path(file.name)

    try:
        _run_checked(f"git commit -F {quote_for_shell(message_path)}")
    finally:
        message_path.unlink(missing_ok=True)

    _run_checked(f"git push -u origin {branch_name}")


def _run_checked(command: str) -> None:
    result = _exec_shell(command, cwd=Path.cwd())
    if result.returncode != 0:
        raise SkillRunnerError(_format_failure("command", command, result))


def _format_failure(step_name: str, command: str, result: subprocess.CompletedProcess[str]) -> str:
    output = (result.stdout or "") + (result.stderr or "")
    return (
        f"Step failed: {step_name}\n"
        f"Command: {command}\n"
        f"Exit Code: {result.returncode}\n"
        f"Output:\n{output}"
    )


def _exec_shell(command: str, cwd: Path) -> subprocess.CompletedProcess[str]:
    if os.name == "nt":
        executable = r"C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe"
        return subprocess.run(  # noqa: S603
            [executable, "-NoProfile", "-Command", command],
            cwd=str(cwd),
            capture_output=True,
            text=True,
            check=False,
        )

    executable = "/bin/sh"
    return subprocess.run(  # noqa: S603
        [executable, "-lc", command],
        cwd=str(cwd),
        capture_output=True,
        text=True,
        check=False,
    )


def quote_for_shell(path: Path) -> str:
    """Quote path for shell command usage."""
    text = str(path)
    return '"' + text.replace('"', '\\"') + '"'


if __name__ == "__main__":
    main()
